### ISSUE TITLE
Aggregate two options

### ISSUE THREAD

**Issue by siroky** [MewsSystems/FuncSharp#72]
- Some(x), Some(y), f => Some(f(x, y))
- Some(x), None, f => Some(x)
- ...
- None, None, f => None

**Comment by KaliCZ** [comment]
Doesn't this result in inconsistent result type? 
Assuming that `f(x, y)` return `z`, you'd need to either return a coproduct of 3 or 4 types 
- Some z
- Some x
- Some y
- None z (Can be same as first if it would still be an option)

Or you'd need to accept 3 different functions resulting in z 
- one taking x and y 
- one taking x
- one taking y

Alternatively you would accept a function accepting option of y and option of x as parameters. In which case this method does exactly nothing, because you need to pass the two options and a function, so you might as well just call the function.

**Comment by siroky** [comment]
This will be for options of same type and the function will also return same type.

**Comment by siroky** [comment]
Duplicates https://github.com/siroky/FuncSharp/issues/73
